//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoutine
    {
        public int ID { get; set; }
        public int DayID { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public int SectionID { get; set; }
        public int TeacherID { get; set; }
        public int SubjectID { get; set; }
    
        public virtual DayInfo DayInfo { get; set; }
        public virtual SectionInfo SectionInfo { get; set; }
        public virtual SubjectInfo SubjectInfo { get; set; }
        public virtual TeacherInfo TeacherInfo { get; set; }
    }
}
