//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayInfo
    {
        public DayInfo()
        {
            this.ClassRoutines = new HashSet<ClassRoutine>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<ClassRoutine> ClassRoutines { get; set; }
    }
}
