//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Main
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSContext : DbContext
    {
        public SMSContext()
            : base("name=SMSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassInfo> ClassInfoes { get; set; }
        public virtual DbSet<ClassRoutine> ClassRoutines { get; set; }
        public virtual DbSet<CurriculumDetail> CurriculumDetails { get; set; }
        public virtual DbSet<DayInfo> DayInfoes { get; set; }
        public virtual DbSet<NoticeInfo> NoticeInfoes { get; set; }
        public virtual DbSet<ResultInfo> ResultInfoes { get; set; }
        public virtual DbSet<SectionInfo> SectionInfoes { get; set; }
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }
        public virtual DbSet<SubjectInfo> SubjectInfoes { get; set; }
        public virtual DbSet<TeacherInfo> TeacherInfoes { get; set; }
        public virtual DbSet<UserCredential> UserCredentials { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
