//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectInfo
    {
        public SubjectInfo()
        {
            this.ClassRoutines = new HashSet<ClassRoutine>();
            this.CurriculumDetails = new HashSet<CurriculumDetail>();
            this.ResultInfoes = new HashSet<ResultInfo>();
            this.TeacherInfoes = new HashSet<TeacherInfo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Code { get; set; }
    
        public virtual ICollection<ClassRoutine> ClassRoutines { get; set; }
        public virtual ICollection<CurriculumDetail> CurriculumDetails { get; set; }
        public virtual ICollection<ResultInfo> ResultInfoes { get; set; }
        public virtual ICollection<TeacherInfo> TeacherInfoes { get; set; }
    }
}
