//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCredential
    {
        public UserCredential()
        {
            this.NoticeInfoes = new HashSet<NoticeInfo>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int UserTypeID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TeacherID { get; set; }
    
        public virtual ICollection<NoticeInfo> NoticeInfoes { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
        public virtual TeacherInfo TeacherInfo { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
